language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

env:
  - PGVERSION=9.4
  - PGVERSION=9.3

before_script:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION
  - psql --version
  - psql -U postgres -c 'create database datability;'