language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

matrix:
  include:
    - addons:
      postgresql: 9.3
    - addons:
      postgresql: 9.4

before_script:
  - psql -U postgres -c 'create database datability;'