language: java

sudo: false

jdk:
  - oraclejdk7

cache:
  directories:
    - '$HOME/.m2/repository'

services:
  - postgresql

addons:
  postgresql: '9.1'

before_script:
    - psql -U postgres -c 'create database datability;'